<?php

namespace SchoolBundle\Repository;

/**
 * TravailRealise
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TravailRealiseRepository extends \Doctrine\ORM\EntityRepository
{
}
