
school:
    resource: "@SchoolBundle/Controller/"
    type:     annotation
    prefix:   /{_locale}/

use:
    resource: '@UserBundle/Controller/'
    type: annotation
    prefix:   /{_locale}/

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    prefix:   /{_locale}/