<?php

namespace Proxies\__CG__\SchoolBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Transport extends \SchoolBundle\Entity\Transport implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'SchoolBundle\\Entity\\Transport' . "\0" . 'ecole', '' . "\0" . 'SchoolBundle\\Entity\\Transport' . "\0" . 'eleves', '' . "\0" . 'SchoolBundle\\Entity\\Transport' . "\0" . 'id', '' . "\0" . 'SchoolBundle\\Entity\\Transport' . "\0" . 'nom', '' . "\0" . 'SchoolBundle\\Entity\\Transport' . "\0" . 'depart', '' . "\0" . 'SchoolBundle\\Entity\\Transport' . "\0" . 'trajet', '' . "\0" . 'SchoolBundle\\Entity\\Transport' . "\0" . 'heureDepart', '' . "\0" . 'SchoolBundle\\Entity\\Transport' . "\0" . 'capacite'];
        }

        return ['__isInitialized__', '' . "\0" . 'SchoolBundle\\Entity\\Transport' . "\0" . 'ecole', '' . "\0" . 'SchoolBundle\\Entity\\Transport' . "\0" . 'eleves', '' . "\0" . 'SchoolBundle\\Entity\\Transport' . "\0" . 'id', '' . "\0" . 'SchoolBundle\\Entity\\Transport' . "\0" . 'nom', '' . "\0" . 'SchoolBundle\\Entity\\Transport' . "\0" . 'depart', '' . "\0" . 'SchoolBundle\\Entity\\Transport' . "\0" . 'trajet', '' . "\0" . 'SchoolBundle\\Entity\\Transport' . "\0" . 'heureDepart', '' . "\0" . 'SchoolBundle\\Entity\\Transport' . "\0" . 'capacite'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Transport $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setNom($nom)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNom', [$nom]);

        return parent::setNom($nom);
    }

    /**
     * {@inheritDoc}
     */
    public function getNom()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNom', []);

        return parent::getNom();
    }

    /**
     * {@inheritDoc}
     */
    public function setDepart($depart)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDepart', [$depart]);

        return parent::setDepart($depart);
    }

    /**
     * {@inheritDoc}
     */
    public function getDepart()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDepart', []);

        return parent::getDepart();
    }

    /**
     * {@inheritDoc}
     */
    public function setTrajet($trajet)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTrajet', [$trajet]);

        return parent::setTrajet($trajet);
    }

    /**
     * {@inheritDoc}
     */
    public function getTrajet()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTrajet', []);

        return parent::getTrajet();
    }

    /**
     * {@inheritDoc}
     */
    public function setHeureDepart($heureDepart)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHeureDepart', [$heureDepart]);

        return parent::setHeureDepart($heureDepart);
    }

    /**
     * {@inheritDoc}
     */
    public function getHeureDepart()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHeureDepart', []);

        return parent::getHeureDepart();
    }

    /**
     * {@inheritDoc}
     */
    public function setCapacite($capacite)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCapacite', [$capacite]);

        return parent::setCapacite($capacite);
    }

    /**
     * {@inheritDoc}
     */
    public function getCapacite()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCapacite', []);

        return parent::getCapacite();
    }

    /**
     * {@inheritDoc}
     */
    public function setEcole(\SchoolBundle\Entity\Ecole $ecole = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEcole', [$ecole]);

        return parent::setEcole($ecole);
    }

    /**
     * {@inheritDoc}
     */
    public function getEcole()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEcole', []);

        return parent::getEcole();
    }

    /**
     * {@inheritDoc}
     */
    public function addElefe(\UserBundle\Entity\Eleve $elefe)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addElefe', [$elefe]);

        return parent::addElefe($elefe);
    }

    /**
     * {@inheritDoc}
     */
    public function removeElefe(\UserBundle\Entity\Eleve $elefe)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeElefe', [$elefe]);

        return parent::removeElefe($elefe);
    }

    /**
     * {@inheritDoc}
     */
    public function getEleves()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEleves', []);

        return parent::getEleves();
    }

}
