<?php

namespace Proxies\__CG__\SchoolBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Programme extends \SchoolBundle\Entity\Programme implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'SchoolBundle\\Entity\\Programme' . "\0" . 'enseignant', '' . "\0" . 'SchoolBundle\\Entity\\Programme' . "\0" . 'matiere', '' . "\0" . 'SchoolBundle\\Entity\\Programme' . "\0" . 'salle', '' . "\0" . 'SchoolBundle\\Entity\\Programme' . "\0" . 'classe', '' . "\0" . 'SchoolBundle\\Entity\\Programme' . "\0" . 'horraire', '' . "\0" . 'SchoolBundle\\Entity\\Programme' . "\0" . 'jour', '' . "\0" . 'SchoolBundle\\Entity\\Programme' . "\0" . 'id'];
        }

        return ['__isInitialized__', '' . "\0" . 'SchoolBundle\\Entity\\Programme' . "\0" . 'enseignant', '' . "\0" . 'SchoolBundle\\Entity\\Programme' . "\0" . 'matiere', '' . "\0" . 'SchoolBundle\\Entity\\Programme' . "\0" . 'salle', '' . "\0" . 'SchoolBundle\\Entity\\Programme' . "\0" . 'classe', '' . "\0" . 'SchoolBundle\\Entity\\Programme' . "\0" . 'horraire', '' . "\0" . 'SchoolBundle\\Entity\\Programme' . "\0" . 'jour', '' . "\0" . 'SchoolBundle\\Entity\\Programme' . "\0" . 'id'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Programme $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setEnseignant(\UserBundle\Entity\Enseignant $enseignant)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEnseignant', [$enseignant]);

        return parent::setEnseignant($enseignant);
    }

    /**
     * {@inheritDoc}
     */
    public function getEnseignant()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEnseignant', []);

        return parent::getEnseignant();
    }

    /**
     * {@inheritDoc}
     */
    public function setMatiere(\SchoolBundle\Entity\Matiere $matiere)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMatiere', [$matiere]);

        return parent::setMatiere($matiere);
    }

    /**
     * {@inheritDoc}
     */
    public function getMatiere()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMatiere', []);

        return parent::getMatiere();
    }

    /**
     * {@inheritDoc}
     */
    public function setSalle(\SchoolBundle\Entity\Salle $salle)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSalle', [$salle]);

        return parent::setSalle($salle);
    }

    /**
     * {@inheritDoc}
     */
    public function getSalle()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSalle', []);

        return parent::getSalle();
    }

    /**
     * {@inheritDoc}
     */
    public function setClasse(\SchoolBundle\Entity\Classe $classe)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setClasse', [$classe]);

        return parent::setClasse($classe);
    }

    /**
     * {@inheritDoc}
     */
    public function getClasse()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getClasse', []);

        return parent::getClasse();
    }

    /**
     * {@inheritDoc}
     */
    public function setHorraire(\SchoolBundle\Entity\Horraire $horraire)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHorraire', [$horraire]);

        return parent::setHorraire($horraire);
    }

    /**
     * {@inheritDoc}
     */
    public function getHorraire()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHorraire', []);

        return parent::getHorraire();
    }

    /**
     * {@inheritDoc}
     */
    public function setJour(\SchoolBundle\Entity\Jour $jour)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setJour', [$jour]);

        return parent::setJour($jour);
    }

    /**
     * {@inheritDoc}
     */
    public function getJour()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getJour', []);

        return parent::getJour();
    }

}
